### ISSUE TITLE
windows11-classic-context-menu_DoveBoy@1.2: hash check failed

### ISSUE THREAD

**Issue by altboy** [kkzzhizhou/scoop-apps#102]
I'm trying to install via scoop but it's giving an error in the hash file:

Checking hash of W11ClassicMenu.zip ... ERROR Hash check failed!
App:         kkzzhizhou_scoop-apps/windows11-classic-context-menu_DoveBoy
URL:         https://www.sordum.org/files/download/win11-classic-context-menu/W11ClassicMenu.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    40e4a58d2e356ca3fe8a892a1fb92bc0f8543fe735e5629eb8cc5eddc7795dcd
Actual:      765e9a53e61561bc9ee85c4cd05b663782769b5ddfe4de143524ce5cbf522cff

**Comment by DoveBoy** [comment]
scoop install -s <app name>
