### ISSUE TITLE
考虑添加Gitee代理吗？国内访问有时出错导致无法正常同步

### ISSUE THREAD

**Issue by wgll000** [kkzzhizhou/scoop-apps#109]
本人网络环境为校园网，有时在多台电脑上同步时，存在网络不良导致同步更新失败，希望增加gitee国内代理，更新不频繁都无所谓

**Comment by xbxcw** [comment]
我手动改的，把bucket/apps里的所有json，github.com替换成githubfast.com，下载是变快了，但是不能更新了

**Comment by wgll000** [comment]
> 试试这个https://github.com/lzwme/scoop-proxy-cn

谢谢，十分有用

**Comment by kkzzhizhou** [comment]
之前有上过，被gitee down了。
