### ISSUE TITLE
UltraVNC

### ISSUE THREAD

**Issue by Neustradamus** [kkzzhizhou/scoop-apps#119]
Hello @kkzzhizhou,

UltraVNC is old here, it is possible to update?
- https://github.com/kkzzhizhou/scoop-apps/blob/master/bucket/ultravnc.json

Latest UltraVNC build is here:
- https://forum.uvnc.com/viewforum.php?f=56

Thanks in advance.

**Comment by kkzzhizhou** [comment]
如果有软件安装问题，请参考仓库根路径的app-contributor-list.csv到相应的仓库提交issues https://github.com/ScoopInstaller/Extras/blob/42c5a9902c6c9c3fba614c885ca9c1bf52a8d49a/bucket/ultravnc.json

**Comment by Neustradamus** [comment]
@kkzzhizhou: At this time, the latest is 1.4.3.6, you show me 1.4.3.5.
