### ISSUE TITLE
mysql8@8.2.0: hash check failed

### ISSUE THREAD

**Issue by Dormxb** [kkzzhizhou/scoop-apps#123]
WARN  Purging previous failed installation of mysql8.
ERROR 'mysql8' isn't installed correctly.
Removing older version (8.2.0).
'mysql8' was uninstalled.
Installing 'mysql8' (8.2.0) [64bit] from apps bucket
mysql-8.2.0-winx64.zip (241.5 MB) [===========================================================================] 100%
Checking hash of mysql-8.2.0-winx64.zip ... ERROR Hash check failed!
App:         apps/mysql8
URL:         https://dev.mysql.com/get/Downloads/MySQL-8.2/mysql-8.2.0-winx64.zip
First bytes: 50 4B 03 04 0A 00 00 00
Expected:    74654eaae0e0cd8f1329f8cc91279f63
Actual:      e0b9ac00cf136a40020e579a33d080db

**Comment by kkzzhizhou** [comment]
请阅读Readme.
