### ISSUE TITLE
添加这个bucket之后使用search功能报错，但是不影响实际使用

### ISSUE THREAD

**Issue by felix-zheng91** [kkzzhizhou/scoop-apps#145]
1. 问题

![图片](https://github.com/kkzzhizhou/scoop-apps/assets/23047096/a6b1f826-c598-41f3-b10c-e77694cc695e)
已有图上 bucket，新增apps后使用search 报错
![图片](https://github.com/kkzzhizhou/scoop-apps/assets/23047096/7a4e1d20-0617-4616-bc82-0b8badb22fca)
2. 复现方式
删除apps后正常，重新添加报错依然出现。将其他bucket 删除后再添加apps依然报错。
3. 环境信息
Windows 10 + powershell 7.4.2

**Comment by kkzzhizhou** [comment]
修复了https://github.com/kkzzhizhou/scoop-apps/issues/140后未能复现

**Comment by pheotry** [comment]
> 修复了 #140 后未能复现

我也遇到了类似的问题

```
PS C:\Users\lluu> scoop search mpv
MethodInvocationException: C:\Users\lluu\scoop\apps\scoop\current\libexec\scoop-search.ps1:38
Line |
  38 |      if (!$json.RootElement.TryGetProperty('bin', [ref] $bin)) { retur …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "TryGetProperty" with "2" argument(s): "The requested operation requires an element of type
     | 'Object', but the target element has type 'Array'."
Results from local buckets...
```
