### ISSUE TITLE
MethodInvocationException

### ISSUE THREAD

**Issue by zhangyvzhen** [kkzzhizhou/scoop-apps#161]
scoop search wechat
MethodInvocationException: D:\Scoop\apps\scoop\current\libexec\scoop-search.ps1:38
Line |
  38 |      if (!$json.RootElement.TryGetProperty('bin', [ref] $bin)) { retur …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "TryGetProperty" with "2" argument(s): "The requested operation requires an element of type
     | 'Object', but the target element has type 'Array'."
Results from local buckets...

**Comment by kkzzhizhou** [comment]
Please try re-adding the repository; I couldn't reproduce the issue locally.
