### ISSUE TITLE
建议移除多个仓库

### ISSUE THREAD

**Issue by qzydustin** [kkzzhizhou/scoop-apps#17]
建议移除tianzhijiexian/scoop-bucket

1. 仓库已经不更新
2. 和其他仓库重复
3. 仓库中软件的url为不是官方下载地址，为自己上传的地址。例如：https://raw.githubusercontent.com/tianzhijiexian/scoop-packages/master/space-sniffer.zip等等

希望这个合集仓库越来越好！

**Comment by qzydustin** [comment]
建议移除AStupidBear/scoop-bear

1. 仓库不再更新
2. 和其他仓库重复
3. 有些软件失效，例如origin
{
    "version": "9.3",
    "url": "https://sourceforge.net/projects/bearapps/files/OriginLab2016.rar",
    "extract_dir": "OriginLab2016免安装便携版",
    "shortcuts": [["Origin2016/Origin93_64.exe", "OriginLab"]]
}
已经没办法使用了

**Comment by kkzzhizhou** [comment]
> 建议移除tianzhijiexian/scoop-bucket
> 
> 1. 仓库已经不更新
> 2. 和其他仓库重复
> 3. 仓库中软件的url为不是官方下载地址，为自己上传的地址。例如：https://raw.githubusercontent.com/tianzhijiexian/scoop-packages/master/space-sniffer.zip等等
> 
> 希望这个合集仓库越来越好！

好的👌

**Comment by kkzzhizhou** [comment]
已经移除AStupidBear/scoop-bear、tianzhijiexian/scoop-bucket
