### ISSUE TITLE
这咋更新后，就剩3个包了

### ISSUE THREAD

**Issue by oison111** [kkzzhizhou/scoop-apps#170]
![image](https://github.com/user-attachments/assets/bdd919c4-50f5-4bda-a819-df5945f39768)

**Comment by chengnan049** [comment]
![{4A647492-A384-4A1D-9045-1AE219B7448F}](https://github.com/user-attachments/assets/100b2cbc-e979-433b-b484-91ce393fd46e)
+1，我说有个包一更新咋就找不到了

**Comment by ykz0608** [comment]
![image](https://github.com/user-attachments/assets/f488b883-f29e-4ca0-8c29-b810d5e72ca9)
+1 same problem

**Comment by Throokie** [comment]
加1

**Comment by oison111** [comment]
兄弟们，我换成third 这个bucket 了， 
这是网址：
···
https://scoop.sh/#/buckets
https://github.com/cmontage/scoopbucket-third
···
![image](https://github.com/user-attachments/assets/162f298b-4c72-4fa0-92f7-2f30c9e7c978)
@ykz0608 @chengnan049 @Throokie @hoilc

**Comment by zghk** [comment]
+1

**Comment by hoofcushion** [comment]
可以暂时先用 https://github.com/hoofcushion/scoop-apps

**Comment by kkzzhizhou** [comment]
我的我的，就是自动合并脚本提交了个错误写法，已修复，抱歉。
