### ISSUE TITLE
部分参数缺失

### ISSUE THREAD

**Issue by WOSHIZHAZHA120** [kkzzhizhou/scoop-apps#29]
如main的php.json里有个env_set以设置环境变量
但是到这里就没了, 折腾了一晚上环境才发现（

**Comment by kkzzhizhou** [comment]
> 如main的php.json里有个env_set以设置环境变量 但是到这里就没了, 折腾了一晚上环境才发现（

已更新，后续Main仓库存在的包，将优先使用，其次才会使用本仓库。
