### ISSUE TITLE
不能使用search

### ISSUE THREAD

**Issue by AIR-HH** [kkzzhizhou/scoop-apps#32]
如图,删除掉仓库正常，scoop版本为最新版,系统win10
![image](https://user-images.githubusercontent.com/30023208/142444170-31f4e9d5-6abb-42c8-b76f-ce241681c3cf.png)

**Comment by ViCrack** [comment]
这个仓库其中一个软件json写的有问题

**Comment by kkzzhizhou** [comment]
> 如图,删除掉仓库正常，scoop版本为最新版,系统win10 ![image](https://user-images.githubusercontent.com/30023208/142444170-31f4e9d5-6abb-42c8-b76f-ce241681c3cf.png)

此仓库已添加json文件格式检查。
