### ISSUE TITLE
php8.0 安装错误

### ISSUE THREAD

**Issue by WOSHIZHAZHA120** [kkzzhizhou/scoop-apps#34]
![图片](https://user-images.githubusercontent.com/52521836/145669302-29212e4b-83e1-4740-8b81-562f3d4fe5af.png)

可能的错误位置: https://github.com/kkzzhizhou/scoop-apps/blob/master/bucket/php8.0.json#L26

**Comment by kkzzhizhou** [comment]
> ![图片](https://user-images.githubusercontent.com/52521836/145669302-29212e4b-83e1-4740-8b81-562f3d4fe5af.png)
> 
> 可能的错误位置: https://github.com/kkzzhizhou/scoop-apps/blob/master/bucket/php8.0.json#L26

> scoop install php8.0
Installing 'php8.0' (8.0.14) [64bit]
Loading php-8.0.14-Win32-vs16-x64.zip from cache
Checking hash of php-8.0.14-Win32-vs16-x64.zip ... ok.
Extracting php-8.0.14-Win32-vs16-x64.zip ... done.
Linking ~\scoop\apps\php8.0\current => ~\scoop\apps\php8.0\8.0.14
Creating shim for 'php'.
Creating shim for 'php-cgi'.
Persisting conf.d
Running post-install script...
'php8.0' (8.0.14) was installed successfully!
