### ISSUE TITLE
最新一次提交删除了很多文件

### ISSUE THREAD

**Issue by GreenHatHG** [kkzzhizhou/scoop-apps#35]
https://github.com/kkzzhizhou/scoop-apps/commit/5f6d9a905748f6360256cf9625d51b964936b817

**Comment by z775729168** [comment]
可以临时fork自己改一下
https://github.com/z775729168/scoop-apps/commit/3fab51b1d8260d781139353cf7737ac5e91767f5
也可以添加自己需要的仓库

**Comment by kkzzhizhou** [comment]
因为仓库根据规则自动生成，有概率会因为一些原因导致部分仓库收录不全。如发现仓库更新逻辑问题，可以qq邮件交流。
