### ISSUE TITLE
HEU-KMS-Activator 安装错误

### ISSUE THREAD

**Issue by Cielstar** [kkzzhizhou/scoop-apps#38]
![图片](https://user-images.githubusercontent.com/43376740/161560281-8996d141-5d06-4411-bc72-5bed42ef0d9b.png)

**Comment by WOSHIZHAZHA120** [comment]
改bucket名字了？

**Comment by Cielstar** [comment]
> 改bucket名字了？

什么都没动啊，安装目录也都是默认位置，其他软件都可以正常安装更新的
![图片](https://user-images.githubusercontent.com/43376740/163589399-303e115a-3ad2-4360-9709-fed137e555b0.png)

**Comment by WOSHIZHAZHA120** [comment]
那不知道了, 看你文件夹不存在就觉得有点问题
之前我提过一个 #34 就是这个问题

**Comment by Cielstar** [comment]
> 那不知道了, 看你文件夹不存在就觉得有点问题 之前我提过一个 #34 就是这个问题

我的scoop安装时用的是官网那一条命令，所以所有东西都是默认的没改，装的其他软件可以正常安装更新

**Comment by WOSHIZHAZHA120** [comment]
我指的安装是 [使用说明](https://github.com/kkzzhizhou/scoop-apps#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95) 这的 bucket 添加命令

是不是把里面的 ```apps``` 改了

**Comment by WOSHIZHAZHA120** [comment]
![图片](https://user-images.githubusercontent.com/52521836/164407562-b5358e39-4b84-450b-b6e5-151c084473a4.png)
今天回家测试了一下我这里是没问题的

**Comment by kkzzhizhou** [comment]
> ![图片](https://user-images.githubusercontent.com/43376740/161560281-8996d141-5d06-4411-bc72-5bed42ef0d9b.png)

请到相应的仓库反馈。我这边排查到的问题是powershell的rename-item并不支持路径使用*填充，版本5.1.22000.613，系统Windows 11，可以改用Remove-Item实现

```powershell
> Rename-Item -Path ".\HEU_KMS_Activator_v*.exe" -NewName "HEU_KMS_Activator.exe" -Force
Rename-Item : 无法处理参数，因为参数“path”的值无效。请更改“path”参数的值，然后再次运行此操作。
所在位置 行:1 字符: 1
+ Rename-Item -Path ".\HEU_KMS_Activator_v*.exe" -NewName "HEU_KMS_Acti ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Rename-Item]，PSArgumentException
    + FullyQualifiedErrorId : Argument,Microsoft.PowerShell.Commands.RenameItemCommand
```
