### ISSUE TITLE
listary-beta@6.0.5.16: hash check failed

### ISSUE THREAD

**Issue by Dasein1998** [kkzzhizhou/scoop-apps#41]
Checking hash of ListaryInstaller.exe ... ERROR Hash check failed!
App:         apps/listary-beta
URL:         https://www.listary.com/download/beta/listary6/ListaryInstaller.exe
First bytes: 4D 5A 50 00 02 00 00 00
Expected:    5baf39cd63e1d07784f8614fe0ec79fbc1f5ba2f4f8a91d0f2b55b24d493a250
Actual:      daad3ea2580a5bb89a55b98eb86e6dd0ccb807b6014a20f334ef718773d9ec4d

**Comment by kkzzhizhou** [comment]
请阅读README.md。
