### ISSUE TITLE
6.17 提交之后出现循环依赖

### ISSUE THREAD

**Issue by Weidows** [kkzzhizhou/scoop-apps#44]
用的 scoop shovel-core

update/install 都会报错:
```
ERROR Circular dependency detected: '7zip' -> '7zip'.
ERROR Cannot resolve all dependencies
```
回滚到6.17之前的提交就没问题, 

查找了下面这两段, 改了改但并没发现哪里不对

```
"depends": "7zip"
"depends": "main/7zip"
```

**Comment by Weidows** [comment]
😦今天检查了下, 没问题了

**Comment by xianzheTM** [comment]
@Weidows 我的解决方法是：
1. 先安装Base/7zip
2. 然后在[scoop安装路径]\buckets\apps\bucket中删除所有7zip相关的json,12个
3. scoop update *

**Comment by Weidows** [comment]
@xianzheTM 我实际上就删除了 7zip.json 这一个文件就没问题了

**Comment by kkzzhizhou** [comment]
> 发现还是不对, 6.17 那天提交中有个莫名其妙的重命名 `7zip@21.03+zs.json -> 7zip.json`
> 
> https://github.com/kkzzhizhou/scoop-apps/blob/master/bucket/7zip.json#L9
> 
> 在这个文件中sha又需要用到7zip, 出现了循环依赖
> 
> app-contributor-list.txt 里面我没找到其所属项目, 不知道如何解决

app-contributor-list.txt 这个文件已不再更新，请使用app-contributor-list.csv

**Comment by kkzzhizhou** [comment]
> @xianzheTM 我实际上就删除了 7zip.json 这一个文件就没问题了

应该需要安装跟main同名的其他仓库的描述文件（如7zip.json)应该是非常小众的安装需求，找个时间调为，若main有该文件名，则默认重命名。

**Comment by kkzzhizhou** [comment]
> > 发现还是不对, 6.17 那天提交中有个莫名其妙的重命名 `7zip@21.03+zs.json -> 7zip.json`
> > https://github.com/kkzzhizhou/scoop-apps/blob/master/bucket/7zip.json#L9
> > 在这个文件中sha又需要用到7zip, 出现了循环依赖
> > app-contributor-list.txt 里面我没找到其所属项目, 不知道如何解决
> 
> 应该是一个多月前上的，默认采用新版本的7zip产生的重命名问题，当官方的版本低于第三方修改版时，会保留一个修改版的7zip.json，开个列表处理掉这种异常，或者可能也有其他的方式。

已处理。
