### ISSUE TITLE
由于目标计算机积极拒绝，无法连接。 [::ffff:127.0.0.1]:7890 (127.0.0.1:7890)

### ISSUE THREAD

**Issue by xbxcw** [kkzzhizhou/scoop-apps#55]
![image](https://user-images.githubusercontent.com/33365920/189164545-f6c2bfeb-2460-4ee1-aa9e-b952557b591c.png)
请问这是什么远因，这些地址浏览器可以打开，scoop下载不了

**Comment by kkzzhizhou** [comment]
> ![image](https://user-images.githubusercontent.com/33365920/189164545-f6c2bfeb-2460-4ee1-aa9e-b952557b591c.png) 请问这是什么远因，这些地址浏览器可以打开，scoop下载不了

应该是的启用了代理。找一些后台运行的软件中是否有代理。

**Comment by xbxcw** [comment]
> > ![图片](https://user-images.githubusercontent.com/33365920/189164545-f6c2bfeb-2460-4ee1-aa9e-b952557b591c.png)这是什么原因，这些地址浏览器可以打开，瓢下载不了
> 
> 应该是配置了代理。

嗯嗯，谢谢大佬
