### ISSUE TITLE
obs-studio_nickbudi@27.2.3: download via aria2 failed

### ISSUE THREAD

**Issue by yanshibin** [kkzzhizhou/scoop-apps#62]

**Comment by yanshibin** [comment]
ERROR Download failed! (Error 3) Resource was not found
ERROR https://github.com/obsproject/obs-studio/releases/download/27.2.3/OBS-Studio-27.2.3-Full-x64.zip
    referer=https://github.com/obsproject/obs-studio/releases/download/27.2.3/
    dir=D:\scoop\cache
    out=obs-studio_nickbudi#27.2.3#https_github.com_obsproject_obs-studio_releases_download_27.2.3_OBS-Studio-27.2.3-Full-x64.zip

ERROR & 'D:\scoop\apps\aria2\current\aria2c.exe' --input-file='D:\scoop\cache\obs-studio_nickbudi.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=2520 --continue --summary-interval=0 --auto-save-interval=1

**Comment by kkzzhizhou** [comment]
本仓库为合并仓库，请参考仓库目录的[app-contributor-list.csv](https://github.com/kkzzhizhou/scoop-apps/blob/master/app-contributor-list.csv)找到对应的源仓库进行问题反馈。
