### ISSUE TITLE
下载bitcomet 出错，忽视hash也出错

### ISSUE THREAD

**Issue by xbxcw** [kkzzhizhou/scoop-apps#63]
忽视hash也出错
![image](https://user-images.githubusercontent.com/33365920/203013561-dff9196a-1705-4d90-9bc7-9a26ed0a48a9.png)

**Comment by kkzzhizhou** [comment]
本仓库为合并仓库，请参考仓库目录的[app-contributor-list.csv](https://github.com/kkzzhizhou/scoop-apps/blob/master/app-contributor-list.csv)找到对应的源仓库进行问题反馈。
