### ISSUE TITLE
enigma-virtual-box@10.00: hash check failed

### ISSUE THREAD

**Issue by mathtimes** [kkzzhizhou/scoop-apps#66]
# scoop install enigma-virtual-box
Installing 'enigma-virtual-box' (10.00) [64bit] from apps bucket
proxy: https://enigmaprotector.com/assets/files/enigmavb.exe#/install.exe

Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 1cc2a6|OK  |   2.0MiB/s|D:/PATH/Scoop/cache/enigma-virtual-box#10.00#https_enigmaprotector.com_assets_files_enigmavb.exe_install.exe
Download: Status Legend:
Download: (OK):download completed.
Checking hash of enigmavb.exe ... ERROR Hash check failed!
App:         apps/enigma-virtual-box
URL:         https://enigmaprotector.com/assets/files/enigmavb.exe#/install.exe
First bytes: 4D 5A 50 00 02 00 00 00
Expected:    c6feb1ed2b1a2b35531cc118a10b8836ebea7cbc86b1a9a3bafa59419f233a62
Actual:      1f6ab573b027157b2c6326b3e07479f3a00cda542ea8e4c13a88b5df4126e82a

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/kkzzhizhou/scoop-apps/issues/new?title=enigma-virtual-box%4010.00%3a+hash+check+failed

**Comment by kkzzhizhou** [comment]
本仓库为合并仓库，请参考仓库目录的[app-contributor-list.csv](https://github.com/kkzzhizhou/scoop-apps/blob/master/app-contributor-list.csv)找到对应的源仓库进行问题反馈。
