### ISSUE TITLE
SunloginClient@12.0.1.40571: download via aria2 failed

### ISSUE THREAD

**Issue by ustcltx** [kkzzhizhou/scoop-apps#67]
ERROR Download failed! (Error 22) HTTP response header was bad or unexpected
ERROR https://scoop-zapps.ziiyc.com/d/SunloginClient/SunloginClient-12.0.1.40571.exe#/SunloginClient.exe
    referer=https://scoop-zapps.ziiyc.com/d/SunloginClient/SunloginClient-12.0.1.40571.exe#/
    dir=D:\soft\scoop\apps\cache
    out=SunloginClient#12.0.1.40571#https_scoop-zapps.ziiyc.com_d_SunloginClient_SunloginClient-12.0.1.40571.exe_SunloginClient.exe

ERROR & 'D:\soft\scoop\apps\apps\aria2\current\aria2c.exe' --input-file='D:\soft\scoop\apps\cache\SunloginClient.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.3 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=16 --max-connection-per-server=16 --min-split-size=1M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=11588 --continue --summary-interval=0 --auto-save-interval=1

把--input-file里面的referer移除才能下载，可能是服务器配置问题

**Comment by kkzzhizhou** [comment]
本仓库为合并仓库，请参考仓库目录的[app-contributor-list.csv](https://github.com/kkzzhizhou/scoop-apps/blob/master/app-contributor-list.csv)找到对应的源仓库进行问题反馈。
