### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by DestinyHunter** [kkzzhizhou/scoop-apps#7]
搜索的时候 一直 有报错 如图
![image](https://user-images.githubusercontent.com/20897838/110423735-8fe14e00-80dc-11eb-98fe-ac89edeb2e4b.png)

**Comment by kkzzhizhou** [comment]
我这边测试发现没有报错，scoop搜索速度有些慢，可以考虑使用everything配置快捷键进行搜索。
