### ISSUE TITLE
ZYPlayer.json 和 zyplayer.json 文件名冲突

### ISSUE THREAD

**Issue by UnderCooled** [kkzzhizhou/scoop-apps#94]
这两个文件名冲突导致 scoop 同步 buckets 时无法正常更新此仓库数据：
```
error: cannot pull with rebase: You have unstaged changes.
error: Please commit or stash them.
```

git status 输出:
```
D:\Scoop\buckets\zzz>git status
On branch master
Your branch is behind 'origin/master' by 2 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   bucket/ZYPlayer.json

no changes added to commit (use "git add" and/or "git commit -a")
```

Everything 显示仅有一个 zyplayer.json 文件:
![image](https://github.com/kkzzhizhou/scoop-apps/assets/161503/59b026ab-26c5-4d80-9833-b5fff56fab84)

**Comment by Asukaaaaaa** [comment]
到scoop/buckets/apps目录下执行下面这个命令可以去掉这个记录
git update-index --asume-unchanged bucket/ZYPlayer.json

**Comment by UnderCooled** [comment]
多谢提供思路，我后来直接配置这个目录为大小写敏感了，也算是能解决这个问题：
`fsutil file SetCaseSensitiveInfo <PATH> enable`

**Comment by yegetables** [comment]
> fsutil file SetCaseSensitiveInfo <PATH> enable

如果我先删除apps仓库
 `fsutil.exe file SetCaseSensitiveInfo "D:\scoop\buckets\apps" enable`
`错误:  系统找不到指定的文件`
如果我clone它
`错误:  目录不是空的。`
请问你是如何解决的?

**Comment by UnderCooled** [comment]
> > fsutil file SetCaseSensitiveInfo  enable
> 
> 如果我先删除apps仓库 `fsutil.exe file SetCaseSensitiveInfo "D:\scoop\buckets\apps" enable` `错误: 系统找不到指定的文件` 如果我clone它 `错误: 目录不是空的。` 请问你是如何解决的?

你试试看先用 depth=1 克隆，然后设置大小写敏感，再试着 scoop update

**Comment by sanbeichahegongheguo** [comment]
> 到scoop/buckets/apps目录下执行下面这个命令可以去掉这个记录 git update-index --asume-unchanged bucket/ZYPlayer.json

命令写错了，少写了一个一个 s 字母

"""
git update-index --assume-unchanged bucket/ZYPlayer.json
"""
